Add re-export of async_trait
slawlor/ractor pull request #113
Opened 2023-05-13 17:21 UTC by quietlychris

While importing `ractor` into one of my projects, I was trying to re-create the example under `ractor/ractor/examples/supervisor.rs`. However, I was getting an issue around the use of ` #[async_trait::async_trait]` to mark the `impl Actor` for the existing structs. I imagine this didn't come up in development, since the `async_trait` lib is one of the examples. I know for certain libraries, such as `serde`, it's sometimes common to include the `Serialize, Deserialize` traits as re-exported from the base library (sometimes hidden behind a feature flag, if `serde` is optional), which prevents developers from having to manually re-add a second dependency in order to take advantage of it. I've done the same here, which seems to have solved the problem. If you have any questions or would like to discuss more, just let me know!

2023-05-18 16:13 UTC, slawlor requested changes
See above :)

2023-06-04 00:44 UTC, quietlychris commented
Apologies for the delay in updating this; the past few weeks have been quite busy, and I've not had much time for open source work. I've updated the examples to include the new re-exported trait, and things should be up-to-date with `main`.

2023-06-09 23:10 UTC, slawlor approved these changes
LGTM!

2023-06-09 23:12 UTC, slawlor commented
Ah seems formatting needs a quick refresh. `cargo fmt` should do it

2023-06-10 17:37 UTC, quietlychris commented
Just ran `cargo fmt`-- this should fix that CI error!

2023-06-12 14:15 UTC, merged